select * from BO_ZDOCUMENTODESPACHO where BOZDDE_ESTADOEJECUCION = 1 and BOZDDE_CODIGOBODEGAORIGEN = '03' --and BOZDDE_NUMERODOCUMENTO = 'P-GPIAV-00148770'

--select top 10 * from BO_ZPROVEEDORCLIENTE where BOZPCL_CODIGO = '1103654834001'
--select top 10 * from BO_ZPROVEEDORCLIENTE where BOZPCL_CODIGO = '1804758934'
--select top 10 * from BO_ZSUCURSAL where BOZCLI_CODIGO = '1103654834001'

--##############################################################################
--posibles errores de no subir pedidos
--##############################################################################
--update BO_ZPROVEEDORCLIENTE set ADDCA_ESTADOPROVEEDORCLIENTE = 1
--UPDATE BO_ZPROVEEDORCLIENTE SET BOZPCL_ESTADOEJECUCION = 1
--update BO_ZDOCUMENTODESPACHO set BOZDDE_CODIGOBODERUTA = 'PRINCIPAL' where BOZDDE_ESTADOEJECUCION = 1 and BOZDDE_NUMERODOCUMENTO = 'P-GPIAV-00148770'
--eL NUMERO DE TRABAJO DEBE EXISTIR EN BO_ZSUCURSAL EN LA CIUDAD
--update BO_ZDOCUMENTODESPACHO set BOZDDE_NUMEROTRABAJO = 'PÍLLARO' where BOZDDE_ESTADOEJECUCION = 1 and BOZDDE_NUMERODOCUMENTO = 'P-GPIAV-00130310'

--P-GPIAV-00096838
--P-GPIAV-00096865
--P-GPIAV-00096880

--select * from BO_ZDOCUMENTODESPACHO where BOZDDE_NUMERODOCUMENTO = 'P-GPIAV-00129809'
--select * from BO_ZDETALLEDOCUMENTODESPACHO where BOZDDD_NUMERODOCUMENTO = 'P-GPIAV-00129809'

--select top 10 * from BO_PRODUCTO where BOPRO_CODIGO IN ('02-002-37-007601','02-002-14-001301','02-001-34-004701','02-001-15-017001')

--select * from BO_ZDETALLEDOCUMENTODESPACHO WHERE BOZDDD_ESTADOEJECUCION = 1 --and BOZDDD_NUMERODOCUMENTO = 'P-GPCAL-00000075'

--#############################################
--ENVIAR PEDIDOS AL WMS: Descomentamos y corremos
--#############################################
--UPDATE BO_ZDETALLEDOCUMENTODESPACHO
--SET BOZDDD_ESTADOESCRITURA = 2
--WHERE BOZDDD_ESTADOESCRITURA = 1
----*********************************************
--UPDATE BO_ZDOCUMENTODESPACHO
--SET BOZDDE_ESCRITURA = 2
--WHERE BOZDDE_ESCRITURA = 1
--#############################################

--Revisar Despachados
--select COUNT(*) from BO_ZDESPACHOCABECERA_EXPORTACION where BOZDC_NUMERODOCUMENTO like '%P-GPIAV-%' and BOZDC_EXPORTAR = 2 and BOZDC_FECHASCMI >= cast(getdate()-1 as date)
--select * from BO_ZDESPACHOCABECERA_EXPORTACION where BOZDC_NUMERODOCUMENTO like '%P-GPCAL-00003193%' and BOZDC_EXPORTAR = 2 and BOZDC_FECHASCMI >= cast(getdate()-1 as date)
--order by BOZDC_NUMERODOCUMENTO

--Revisar Ingresados
--select * from BO_ZDOCUMENTODESPACHO where BOZDDE_NUMERODOCUMENTO like '%P-GPIAV-%' and bozdde_fechaerp = cast(getdate() as date)
--select * from BO_ZDOCUMENTODESPACHO where BOZDDE_NUMERODOCUMENTO like '%P-GPCAL-%' and bozdde_fechaerp = cast(getdate() as date)
--select * from BO_ZDOCUMENTODESPACHO where BOZDDE_CODIGOCLIENTE like '%1713102612001%' and bozdde_fechaerp = cast(getdate() as date)
--select * from BO_ZDETALLEDOCUMENTODESPACHO where BOZDDD_NUMERODOCUMENTO like '%8288%'

--select * from BO_ZDOCUMENTODESPACHO where BOZDDE_CODIGOCLIENTE = '' AND BOZDDE_FECHAERP = CAST(GETDATE() AS DATE) AND BOZDDE_NUMERODOCUMENTO like '%P-GPCAL-%'

----Borras Pedidos mas Ingresados
--select * from BO_ZDOCUMENTODESPACHO where   BOZDDE_NUMERODOCUMENTO = 'P-GPCAL-00000582' and BOZDDE_CODIGOBODEGAORIGEN = '01'
--select * from BO_ZDETALLEDOCUMENTODESPACHO WHERE BOZDDD_NUMERODOCUMENTO = 'P-GPIAV-00000167' and BOZDDD_CODIGOBODEGAORIGEN = '01'

--1891757995001


--select BOZDC_NUMERODOCUMENTO from BO_ZDESPACHOCABECERA_EXPORTACION where BOZDC_NUMERODOCUMENTO like '%P-GPIAV-%' and BOZDC_EXPORTAR = 2 

--Revisar Pedidos CLiente
--select * from BO_ZDESPACHOCABECERA_EXPORTACION where BOZDC_CODIGOCLIENTE = '2100336284001' AND BOZDC_EXPORTAR = 2

--select * from BO_ZDOCUMENTODESPACHO where BOZDDE_NUMERODOCUMENTO like '%P-GPIAV-00019522%'
--select * from BO_ZDETALLEDOCUMENTODESPACHO where BOZDDD_NUMERODOCUMENTO like '%P-GPIAV-00019522%'

--update BO_ZDOCUMENTODESPACHO 
--set BOZDDE_NUMEROLINEAS = 15--,
----BOZDDE_NUMEROITEM = 12
--where BOZDDE_NUMERODOCUMENTO like '%P-GPIAV-00019522%'

--select BOZDDE_NUMERODOCUMENTO as Pedido,BOZDDE_FECHASCMI as FechaWMS from BO_ZDOCUMENTODESPACHO where BOZDDE_NUMERODOCUMENTO IN
--('P-GPIAV-00004295', 'P-GPIAV-00004297', 'P-GPIAV-00004332', 'P-GPIAV-00004340')


--select * from BO_ZDOCUMENTODESPACHO where BOZDDE_NUMERODOCUMENTO IN 
--('P-GPIAV-00005639','P-GPIAV-00005640')
