use BODEGAS_SCMIALVARADO

select substring(BOPRO_CODIGO,0,15) as articulo
,CCIDG_CANTIDADCONTADA actual
,	CCIGC_EXISTENCIAWMS antes
,	CCIGC_DIFERENCIA diferencia
,BOCOO_CODIGO coordenada 
,b.ADUSU_NOMBRE +' ' +b.ADUSU_APELLIDO as Nombres
,b.ADUSU_USUARIO Usuario
from CC_INVENTARIODETALLADOGRUPOCONTROL A inner join AD_USUARIO B ON A.CCIDG_USUARIO=B.ADUSU_CODIGO  
where cast(CCIDG_FECHAINICIO as date) > '30/06/2017' AND 
b.ADUSU_APELLIDO like '%Chamba%'
